import subprocess
import re
import os
import requests
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

app = FastAPI(title="RunbookAI Mini Backend")

# Enable CORS for local development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class LogRequest(BaseModel):
    log_text: str

class ExecRequest(BaseModel):
    script: str

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434/api/generate")

def parse_ollama_response(raw_text: str):
    """
    Parses Ollama output to extract the root cause and the fix script block.
    """
    root_cause = ""
    fix_script = ""
    
    # Extract Root Cause (look for ROOT CAUSE: and stop before FIX SCRIPT or backticks)
    rc_match = re.search(r'(?i)root\s*cause\s*:\s*(.*?)(?=\n\s*(?:fix\s*script|```|$))', raw_text, re.DOTALL)
    if rc_match:
        root_cause = rc_match.group(1).strip()
    else:
        # Fallback to searching line-by-line
        for line in raw_text.splitlines():
            if line.upper().startswith("ROOT CAUSE:"):
                root_cause = line[11:].strip()
                break
    
    # Extract Fix Script (look for code blocks)
    code_blocks = re.findall(r'```(?:bash|sh|shell)?\n(.*?)\n```', raw_text, re.DOTALL | re.IGNORECASE)
    if code_blocks:
        fix_script = code_blocks[0].strip()
    else:
        # Fallback to general code block backticks
        code_blocks_generic = re.findall(r'```(.*?)\n```', raw_text, re.DOTALL)
        if code_blocks_generic:
            fix_script = code_blocks_generic[0].strip()
        else:
            # Fallback to everything after FIX SCRIPT: header
            parts = re.split(r'(?i)fix\s*script\s*:', raw_text)
            if len(parts) > 1:
                fix_script = parts[1].strip()
                
    # Set default values if parsing was completely empty
    if not root_cause:
        root_cause = "Could not parse root cause. See raw analysis response below."
    if not fix_script:
        fix_script = "# No executable fix script was generated by the AI."
        
    return {
        "root_cause": root_cause,
        "fix_script": fix_script
    }

@app.post("/api/analyze")
async def analyze_log(req: LogRequest):
    prompt = (
        f"You are a Linux SysAdmin. Analyze this error:\n{req.log_text}\n\n"
        f"Respond ONLY in this format:\n"
        f"ROOT CAUSE: <one sentence reason>\n"
        f"FIX SCRIPT:\n"
        f"```bash\n"
        f"<commands>\n"
        f"```"
    )
    
    try:
        response = requests.post(OLLAMA_URL, json={
            "model": "gemma4:e2b",
            "prompt": prompt,
            "stream": False
        }, timeout=300)
        
        if response.status_code != 200:
            raise HTTPException(status_code=500, detail=f"Ollama returned status {response.status_code}: {response.text}")
            
        raw_analysis = response.json().get("response", "")
        parsed = parse_ollama_response(raw_analysis)
        
        return {
            "raw_analysis": raw_analysis,
            "root_cause": parsed["root_cause"],
            "fix_script": parsed["fix_script"]
        }
    except requests.exceptions.RequestException as e:
        return {
            "raw_analysis": f"Error connecting to Ollama: {str(e)}",
            "root_cause": "Ollama service is unreachable. Make sure Ollama is running locally and model gemma4:e2b is loaded.",
            "fix_script": "# Ollama offline. Cannot diagnose automatically.\necho 'Error: Ollama connection failed.'"
        }

@app.post("/api/simulate")
async def simulate_break():
    filepath = os.path.abspath("test-service.conf")
    try:
        # Create config file
        with open(filepath, "w") as f:
            f.write("PORT=8080\nDB_HOST=localhost\nDEBUG=True\n")
        # Strip all permissions (chmod 000)
        os.chmod(filepath, 0o000)
        return {"status": "success", "filepath": filepath}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/simulate/status")
async def check_simulation_status():
    filepath = os.path.abspath("test-service.conf")
    if not os.path.exists(filepath):
        return {"exists": False, "readable": False, "permissions": "N/A"}
    try:
        with open(filepath, "r") as f:
            f.read()
        readable = True
    except PermissionError:
        readable = False
    except Exception:
        readable = False
    
    stat = os.stat(filepath)
    perms = oct(stat.st_mode & 0o777)
    return {"exists": True, "readable": readable, "permissions": perms}

@app.post("/api/execute")
async def execute_script(req: ExecRequest):
    try:
        # Run command locally with a 15 second timeout to prevent hangs
        result = subprocess.run(
            req.script, 
            shell=True, 
            text=True, 
            capture_output=True, 
            timeout=15
        )
        return {
            "exit_code": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr
        }
    except subprocess.TimeoutExpired as e:
        return {
            "exit_code": -1,
            "stdout": e.stdout or "",
            "stderr": f"Execution timed out after 15 seconds.\nStderr output so far: {e.stderr or ''}"
        }
    except Exception as e:
        return {
            "exit_code": -1,
            "stdout": "",
            "stderr": str(e)
        }

@app.get("/api/health")
async def health_check():
    ollama_ok = False
    try:
        # Check if Ollama tags endpoint is reachable
        tags_url = OLLAMA_URL.rsplit("/", 1)[0] + "/tags"
        res = requests.get(tags_url, timeout=2)
        if res.status_code == 200:
            ollama_ok = True
    except Exception:
        pass
    return {
        "backend": "ok",
        "ollama": "ok" if ollama_ok else "offline"
    }

# Mount frontend directory for static serving
frontend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "frontend"))
if not os.path.exists(frontend_dir):
    os.makedirs(frontend_dir, exist_ok=True)

# Mount frontend static files last, so they don't override the API routes
app.mount("/", StaticFiles(directory=frontend_dir, html=True), name="frontend")
